[package]
name = "sagelib"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[features]
default = ["node"]
node = ["napi", "napi-derive", "napi-build"]
python = ["pyo3"]

[dependencies]
napi = { version = "2", default-features = false, features = ["napi4"], optional = true }
napi-derive = { version = "2", optional = true }
pyo3 = { version = "0.21.0", default-features = false, features = ["extension-module", "abi3-py38", "macros"], optional = true }
glob = "0.3"
regex = "1.10"

[build-dependencies]
napi-build = { version = "2", optional = true }
