name: Release to Test PyPI

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build and Publish PyPI
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable-x86_64-pc-windows-msvc

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install maturin
        run: pip install maturin

      - name: Build Python wheels
        run: maturin build --release --features python

      - name: Publish to Test PyPI
        env:
          MATURIN_PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: maturin upload --repository-url https://test.pypi.org/legacy/ target/wheels/*.whl
